PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX dcelements: <http://purl.org/dc/elements/1.1/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

SELECT ?title ?description ?version
WHERE {
    ?subject dcelements:title ?title.
    OPTIONAL{?subject dcelements:description ?description.}
    OPTIONAL{?subject owl:versionInfo ?version.}
}