PREFIX dc: <http://dublincore.org/specifications/dublin-core/dcmi-terms/2012-06-14/>
PREFIX ns: <http://www.w3.org/2003/06/sw-vocab-status/ns#>
PREFIX bfo: <http://purl.obolibrary.org/obo/bfo/2019-08-26/bfo.owl#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xml: <http://www.w3.org/XML/1998/namespace>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX aeon: <https://github.com/tibonto/aeon#>
PREFIX obda: <https://w3id.org/obda/vocabulary#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX dcelements: <http://purl.org/dc/elements/1.1/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX iao: <http://purl.obolibrary.org/obo/iao/2020-06-10/iao.owl#>
SELECT 
   ?term ?versionInfo ?title ?description ?IRI
WHERE {
    OPTIONAL{?term dcterms:title|dcelements:title ?title.}
	OPTIONAL{?term dcterms:description|dcelements:description ?description.}
	OPTIONAL{?term owl:versionInfo ?versionInfo.}
	OPTIONAL{?term owl:versionIRI  ?IRI}
#:title ?seeAlso
}
ORDER BY ?type
